### ISSUE TITLE
Increasing the # of users of the source{d} stack

### ISSUE THREAD

**Issue by marnovo** [src-d/okrs#10]
**Parent objective:**  #2
**Progress:** 0%

- [ ] [P0] Make MLonCode a thing #49
- [ ] [P0] Make source{d} the face of MLonCode #50
- [ ] [P0] Make source{d} the lead of MLonCode research #42 
- [ ] [P0] Make source{d} the to-go place for MLonCode models #44
- [ ] [P0] Release updated content for sourced.tech #13

**Comment by bzz** [comment]
To increase the number, I guess we might need to measure it or some kind of proxy. 
Is there already existing one we want to use?

**Comment by campoy** [comment]
There's an OKR related to tracking metrics, one of them is how many users we have, on #48

**Comment by marnovo** [comment]
[OKRs Review] Reminder to @marnovo: Link KRs to https://github.com/src-d/okrs/issues/48

**Comment by marnovo** [comment]
@eiso maybe some of these KRs belong to #1 instead of here?

**Comment by eiso** [comment]
I am comfortable with it being here actually since they are all to increase exposure.

**Comment by marnovo** [comment]
[P0] Make MLonCode a thing #49 -> Needs DevRel KR update, but likely no
[P0] Make source{d} the face of MLonCode #50 -> Needs DevRel KR update, but likely no
[P0] Make source{d} the lead of MLonCode research #42 -> Only the conferences achieved
[P0] Make source{d} the to-go place for MLonCode models #44 -> Started draft but blocked by refactoring of Modelforge
[P0] Release updated content for sourced.tech #13 -> About 1/3 of the process, content/visual directions the current stage
