### ISSUE TITLE
Users are able to work with PGA

### ISSUE THREAD

**Issue by marnovo** [src-d/okrs#11]
**Parent objective:**  #2
**Progress:** 1/3

- [x] [P0] Make engine suitable to run over PGA #17 
- [ ] [P0] Make UAST usable without extensive knowledge of Babelfish #12 
- [ ] [P1] Set PGA update policy and perform it #41

**Comment by marnovo** [comment]
[OKRs Review]

- Removed `[P0] Facilitate UAST-based tasks on PGA #18` from parent.
- Added to parent `[P1] Set PGA update policy and perform it #41`

All of these (that was on parent) are covered by OKRs already:

> * successfully download
> * filter & process PGA to extract roles
> * semantic concepts using XPath
> * data is fresh

**Comment by marnovo** [comment]
[P0] Make engine suitable to run over PGA #17 -> Done
[P0] Make UAST usable without extensive knowledge of Babelfish #12 -> High level abstractions close to done, Babelfish playground update done, formal satisfaction research blocked
[P1] Set PGA update policy and perform it #41 -> Not done, some discussions and moved to 3Q18
