### ISSUE TITLE
Release updated content for sourced.tech

### ISSUE THREAD

**Issue by marnovo** [src-d/okrs#13]
**Parent objective:**  #10 
**Progress:** 0%

- [ ] [P0] Create a content strategy plan #35 
- [ ] [P1] Update brand touchpoints according to content plan 
- [ ] [P1] Apply new Visual Style to sourced.tech #32 
- [ ] [P1] Write 2 blog posts in 2Q18 https://github.com/src-d/okrs/issues/38

**Comment by ricardobaeta** [comment]
@marnovo 

- [ ] [PO] Create a Content Strategy Plan 
        - [ ] Editorial Environment Setup
        - [ ] Costumer Journeys
        - [ ] Content Model
        - [ ] Information Architecture
        - [ ] Copywriting
        - [ ] Establish a Content Management Plan
        - [ ] Metrics & Evaluation Analytics Setup
- [ ] [P1] Write 2 blog posts in 2Q18 
        - [ ] CAT Case-Study Development Post

**Comment by marnovo** [comment]
[P0] Create a content strategy plan #35 -> Partially done, needs to be finished
[P1] Update brand touchpoints according to content plan -> Depends on KR above
[P1] Apply new Visual Style to sourced.tech #32 -> Partially done, needs to be finished
[P1] Write 2 blog posts in 2Q18 #38 -> 1 out of two 2 PRed, needs review/publishing.
