### ISSUE TITLE
UAST structure normalization

### ISSUE THREAD

**Issue by dennwc** [src-d/okrs#22]
**Parent objective:**  #21
**Progress:** 2/4

- [x] [P0] Refactor SDK to better support structure manipulation (https://github.com/bblfsh/sdk/issues/240)
- [x] [P0] Design and implement transformation DSL (https://github.com/bblfsh/sdk/issues/241)
- [ ] [P0] Port existing annotation code (https://github.com/bblfsh/sdk/issues/244)

**Comment by marnovo** [comment]
[OKRs Review] Since it's overly detailed for OKRs and related to tasks, discarding.
