### ISSUE TITLE
Launch gitbase and its playground

### ISSUE THREAD

**Issue by marnovo** [src-d/okrs#8]
**Parent objective:**  #2 
**Progress:** 0%

- [x] [P0] Launch a beta version of the single node version of gitbase #16
- [x] [P0] Design gitbase playground #39
- [x] [P0] Build gitbase playground #51 
- [ ] [P1] Get over 2/3 of user positive feedback

**Comment by smola** [comment]
@marnovo @eiso  Maybe here Key Result "Launch the hosted playground of gitbase" and Objective "Launch a beta version of the single node version of gitbase with indices" should be inverted? Other key results look like part of the former, not the later.

Also, "with indices" is an engineering detail of the more broad objective of improving performance.

**Comment by ricardobaeta** [comment]
@marnovo [P0] Design gitbase playground is accomplished https://github.com/src-d/okrs/issues/39

**Comment by bzz** [comment]
@marnovo [P0] Build gitbase playground is accomplished #51

**Comment by marnovo** [comment]
[P1] Get over 2/3 of user positive feedback -> Formal % still missing
